# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 21:49
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='news',
            name='isPublished',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
