# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 22:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20171103_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='news',
            name='publishedAt',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='isPublished',
            field=models.BooleanField(default=False),
        ),
    ]
